### PR TITLE
Match brackets in math environments

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Fixes https://github.com/vn-ki/bracket-colorizer/issues/23.

### CODE REVIEW

**Comment by UziTech** [comment]
I added a test for latex.

Does this look right? or should the brackets around `\[E=mc^2\]` also be colorized?

image

**Comment by BeastyBlacksmith** [comment]
well, the question is, if you want to treat the math environment limiters (`$ $`, `$$ $$` and `\[ \]`)l as "brackets" in general.
Than it should be colorized otherwise its okay as it is.
Maybe adding some nested brackets in the tests does not hurt. Like
`the reduced volume $$v = \frac{V}{\frac{4\pi}{3}\Rve^3} = 6\sqrt{\pi} \frac{V}{A^{\frac{3}{2}}}$$`

**Comment by UziTech** [comment]
Do we need to exclude the plain text?

image

**Comment by UziTech** [comment]
maybe check for latex grammar and use different scopes?

```js
const grammar = this.editor.getGrammar().name;
if (grammar === "LaTeX") {
  if (scope.includes('math') || scope.includes('punctuation')) {
    return false;
  }
  if (scope.includes('text')) {
    return true;
  }
}
```

**Comment by BeastyBlacksmith** [comment]
I don't really understand. I would still want to have colored brackets in written text like
```latex
This is (what I meant).
```
Having stuff in raw single or double quotes gets linted in my editor as invalid syntax (probably by another package).
Screenshot from 2019-07-12 19-01-01

**Comment by UziTech** [comment]
I'm ok with it if your are. I don't know enough about latex to know if this will happen:

image

**Comment by BeastyBlacksmith** [comment]
I can't think of a use case, that would have an issue with this, so I am in favour of keeping it as it is.

**Pull request merged**
